### ISSUE TITLE
[v0.9.x] Error: Cannot find module 'mongodb'

### ISSUE THREAD

**Issue by ahwayakchih** [ahwayakchih/openshift-nodebb#18]
After running `npm install --production`, without running `nodebb setup`, i got this:

```
5/3 08:58 [132764] - error: Unable to initialize MongoDB! Is MongoDB installed? Error :Cannot find module 'mongodb'
5/3 08:58 [132764] - error: Error: Cannot find module 'mongodb'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.init (/var/lib/openshift/56d9a5ce7628e14f71000062/app-root/runtime/repo/src/database/mongo.js:52:18)
    at /var/lib/openshift/56d9a5ce7628e14f71000062/app-root/runtime/repo/node_modules/async/lib/async.js:760:23
    at /var/lib/openshift/56d9a5ce7628e14f71000062/app-root/runtime/repo/node_modules/async/lib/async.js:166:37
    at fn (/var/lib/openshift/56d9a5ce7628e14f71000062/app-root/runtime/repo/node_modules/async/lib/async.js:746:34)
    at /var/lib/openshift/56d9a5ce7628e14f71000062/app-root/runtime/repo/node_modules/async/lib/async.js:1213:16
    at /var/lib/openshift/56d9a5ce7628e14f71000062/app-root/runtime/repo/node_modules/async/lib/async.js:166:37
```

Looks like the problem mentioned in #13.

It looks like NodeBB builds that module dynamically at setup and running `npm install` later removes that module.

**Comment by ahwayakchih** [comment]
Looks like this happens after `npm --prune`. Old nodejs module did not call that, but the one we switched to does.

NodeBB 1.x does not install database modules dynamically anymore. Now they're part of dependencies in `package.json`. Which means, there's not much point trying to workaround this problem.
